version: '2'
services:
  db:
    image: postgres:12.12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  backend:
    image: gerrome/java-angular-stack_backend:1
    #build: backend/.
    ports: 
      - "8080:8080"
    depends_on:
      - db
  frontend:
    image: gerrome/java-angular-stack_frontend:1
    #build: frontend/.
    ports: 
      - "80:80"
    depends_on: 
      - backend
